[metadata]
name = ezinsar
version = 1.1.3
author = Alexis Hrysiewicz
author_email = alexis.hrysiewicz@ucd.ie
maintainer = Alexis Hrysiewicz
maintainer_email = alexis.hrysiewicz@ucd.ie
description = EZ-InSAR Desktop Module
long_description_content_type = text/x-rst
license = GPL-v3
url = https://github.com/alexisInSAR/EZ-InSAR-Module-Desktop.git

classifiers =
    Development Status :: 3 - Alpha
    Intended Audience :: Developers
    License :: OSI Approved :: GPL-v3
    Operating System :: OS Independent
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11

[options]
packages = find:
python_requires = >=3.8

[project.entry-points."jupyter_client.kernel_provisioners"]
local-provisioner = "jupyter_client.provisioning:LocalProvisioner"