function mintpy_API_tsview(src,evt,action,miesar_para)
%   Function to interface the view.py from MintPy
%
%   See also mintpy_allstep, mintpy_API_tsview, mintpy_parameters, mintpy_API_plot_trans, mintpy_API_view, mintpy_processing, mintpy_API_save, mintpy_network_plot.
%
%   Copyright 2022 Alexis Hrysiewicz, UCD / iCRAG2
%   Version: 1.0.0
%   Date: 17/02/2020

%% Create the GUI
figapimintpytsview = uifigure('Position',[200 100 1000 800],'Name','MintPy''s TSview.py Application');
glapimintpytsview = uigridlayout(figapimintpytsview,[20 5]);

tbapimintpytsview = uitoolbar(figapimintpytsview);
helpapimintpytsview = uipushtool(tbapimintpytsview);
helpapimintpytsview.Icon = fullfile(matlabroot,'toolbox','matlab','icons','help_ex.png');
helpapimintpytsview.Tooltip = 'Help';
helpapimintpytsview.ClickedCallback = @help_mintpy_API_tsview;

    function help_mintpy_API_tsview(src,event)
        cmd = {'Help for tsview.py';...
            '---------------------------------------';
            'Please:';
            '1) Select your dataset(s)';
            '2) Modify the parameters (yes/no or VALUE)';
            '3) Run'};
        boxtmp = msgbox(cmd, 'Help','Help for tsview.py');
    end 

titleapimintpytsview = uilabel(glapimintpytsview,'Text','MintPy''s TSview.py Application','HorizontalAlignment','center','VerticalAlignment','center','FontSize',30,'FontWeight','bold');
titleapimintpytsview.Layout.Row = [1 2];
titleapimintpytsview.Layout.Column = [1 5];

labeldatasetapimintpytsview = uilabel(glapimintpytsview,'Text','Dataset:','HorizontalAlignment','Left','VerticalAlignment','center','FontSize',15,'FontWeight','bold');
labeldatasetapimintpytsview.Layout.Row = [3];
labeldatasetapimintpytsview.Layout.Column = [1 5];

datasetapimintpytsview = uilistbox(glapimintpytsview,'Multiselect','on');
datasetapimintpytsview.Layout.Row = [4 5];
datasetapimintpytsview.Layout.Column = [1 5];

labeltableapimintpytsview = uilabel(glapimintpytsview,'Text','Selection of parameters:','HorizontalAlignment','Left','VerticalAlignment','center','FontSize',15,'FontWeight','bold');
labeltableapimintpytsview.Layout.Row = [6];
labeltableapimintpytsview.Layout.Column = [1 5];

tableapimintpytsview = uitable(glapimintpytsview,'ColumnEditable',[false true false]);
tableapimintpytsview.Layout.Row = [7 19];
tableapimintpytsview.Layout.Column = [1 5];

buttonapimintpytsview = uibutton(glapimintpytsview,'Text','Run','ButtonPushedFcn', @(btn,event) run_api_tsview(btn,event));
buttonapimintpytsview.Layout.Row = [20];
buttonapimintpytsview.Layout.Column = [1 5];

%% Initialisation of datasets

% Load the MintPy directory
fi = fopen([miesar_para.WK,'/mintpydirectory.log'],'r');
pathmintpyprocessing = textscan(fi,'%s'); fclose(fi); pathmintpyprocessing = pathmintpyprocessing{1}{1};

%% Check the possible datasets
list_data_set = dir(pathmintpyprocessing);
data_set = cell(1);
h = 1;
for i1 = 1 : length(list_data_set)
    if isempty(strfind(list_data_set(i1).name,'timeseries')) == 0 & isempty(strfind(list_data_set(i1).name,'.h5')) == 0
        data_set{h} = list_data_set(i1).name;
        h = h + 1;
    end

end

list_data_set = dir([pathmintpyprocessing,'/geo']);
for i1 = 1 : length(list_data_set)
    if isempty(strfind(list_data_set(i1).name,'timeseries')) == 0 & isempty(strfind(list_data_set(i1).name,'.h5')) == 0
        data_set{h} = list_data_set(i1).name;
        h = h + 1;
    end
end

%% Modification of dropdown
datasetapimintpytsview.Items = data_set;
datasetapimintpytsview.Value = data_set{end};

%% Create the parameter table
paratable = {'--label','','[FILE_LABEL [FILE_LABEL ...]] labels to display for multiple input files';...
    '--ylim','','YMIN YMAX Y limits for point plotting.';...
    '--tick-right','no','set tick and tick label to the right';...
    '--lookup','','lookup table file';...
    '-n','','Epoch/slice number for initial display.';...
    '--error','','txt file with error for each date.';...
    '--start-date','','start date of displacement to display';...
    '--end-date','','end date of displacement to display';...
    '--exclude','','[EX_DATE_LIST [EX_DATE_LIST ...]], --ex [EX_DATE_LIST [EX_DATE_LIST ...]] Exclude date shown as gray.';...
    '--zero-first','no','Set displacement at first acquisition to zero.';...
    '--offset','','Offset for each timeseries file.';...
    '--noverbose','no','Disable the verbose message printing.';...
    '--nofit','no','Do not plot the prediction of the time function (deformation model) fitting.';...
    '--plot-fit-conf-int','no','Plot the time function prediction confidence intervals. [!-- Preliminary feature alert! --!] [!-- This feature is NOT throughly checked. Read the code before use. Interpret at your own risk! --!]';...
    '--memory','','Max amount of memory in GB to use (default: 4.0). Adjust according to your computer memory.';...
    '--poly-order','','a polynomial function with the input degree (default: 1). E.g.: --poly 1 # linear --poly 2 # quadratic --poly 3 # cubic';...
    '--periodic','','PERIODIC [PERIODIC ...] periodic function(s) with period in decimal years (default: []). E.g.:  --periodic 1.0  # an annual cycle --periodic 1.0 0.5 # an annual cycle plus a semi-annual cycle';...
    '--step','','STEP [STEP ...] step function(s) at YYYYMMDD (default: []). E.g.: --step 20061014 # coseismic step  at 2006-10-14T00:00 --step 20110311 20120928T1733 # coseismic steps at 2011-03-11T00:00 and 2012-09-28T17:33';...
    '--exponential','','EXP [EXP ...] exponential function(s) at YYYYMMDD with characteristic time(s) tau in decimal days (default: []). E.g.: --exp  20181026 60 # exp onset at 2006-10-14T00:00 with tau=60 days --exp  20181026T1355 60 120 # exp onset at 2006-10-14T13:55 with tau=60 days overlayed by a tau=145 days --exp  20161231 80.5 --exp 20190125 100  # 1st exp onset at 2011-03-11 with tau=80.5 days and 2nd exp onset at 2012-09-28 with tau=100  days';...
    '--logarithmic','','LOG [LOG ...] logarithmic function(s) at YYYYMMDD with characteristic time(s) tau in decimal days (default: []). E.g.: --log  20181016 90.4                      # log onset at 2006-10-14T00:00 with tau=90.4 days --log  20181016T1733 90.4 240             # log onset at 2006-10-14T17:33 with tau=90.4 days overlayed by a tau=240 days --log  20161231 60 --log 20190125 180.2   # 1st log onset at 2011-03-11 with tau=60 days and # 2nd log onset at 2012-09-28 with tau=180.2 days';...
    '--yx','','Y X initial pixel to plot in Y/X coord';...
    '--lalo','','LAT LON initial pixel to plot in lat/lon coord';...
    '--marker','','marker style (default: o).';...
    '--markersize','','marker size (default: 6.0).';...
    '--linewidth','','line width (default: 0).';...
    '--edgewidth','','Edge width for the error bar (default: 1.0)';...
    '--vlim', '' ,'Display limits for matrix plotting.';...
    '--unit', '' ,'unit for display.  Its priority > wrap';...
    '--wrap',   'no' ,'';...
    '--wrap-range', '',' MIN MAX  range of one cycle after wrapping (default: [-3.141592653589793, 3.141592653589793]).';...
    '--flip-lr','no','flip left-right';...
    '--flip-ud','no','flip up-down';...
    '--noflip','no','turn off auto flip for radar coordinate file';...
    '--num-multilook','','multilook data in X and Y direction with a factor for display (default: 1).';...
    '--no-multilook','no', 'do not multilook, for high quality display. If multilook is True and multilook_num=1, multilook_num will be estimated automatically. Useful when displaying big datasets.';...
    '--alpha','','Data transparency. 0.0 - fully transparent, 1.0 - no transparency.';...
    '--dem','','DEM file to show topography as background';...
    '--mask-dem','no','Mask out DEM pixels not coincident with valid data pixels';...
    '--dem-noshade','no','do not show DEM shaded relief';...
    '--dem-nocontour','no','do not show DEM contour lines';...
    '--contour-smooth','','Background topography contour smooth factor - sigma of Gaussian filter. Set to 0.0 for no smoothing; (default: 3.0).';...
    '--contour-step','','Background topography contour step in meters (default: 200.0).';...
    '--contour-linewidth','','Background topography contour linewidth (default: 0.5).';...
    '--shade-az','','The azimuth (0-360, degrees clockwise from North) of the light source (default: 315.0).';...
    '--shade-alt','','The altitude (0-90, degrees up from horizontal) of the light source (default: 45.0).';...
    '--shade-min','','The min height in m of colormap of shaded relief topography (default: -4000.0).';...
    '--shade-max','','The max height of colormap of shaded relief topography (default: max(DEM)+2000).';...
    '--shade-exag','','Vertical exaggeration ratio (default: 0.5).';...
    '--fontsize','','font size';...
    '--fontcolor','','font color (default: k).';...
    '--nowhitespace','no','do not display white space';...
    '--noaxis','no','do not display axis';...
    '--notick','no','do not display tick in x/y axis';...
    '--colormap','','colormap used for display, i.e. jet, cmy, RdBu, hsv, jet_r, temperature, viridis, etc. More at https://mintpy.readthedocs.io/en/latest/api/colormaps/';...
    '--cmap-lut','','number of increment of colormap lookup table (default: 256).';...
    '--cmap-vlist','','list of 3 float numbers, for truncated colormap only (default: [0.0, 0.7, 1.0]).';...
    '--nocolorbar','no','do not display colorbar';...
    '--cbar-nbins','','number of bins for colorbar.';...
    '--cbar-ext','','{both,max,None,min,neither} Extend setting of colorbar; based on data stat by default.';...
    '--cbar-label','','colorbar label colorbar location for single plot (default: right).';...
    '--cbar-size','','colorbar size and pad (default: 2%).';...
    '--notitle','no','do not display title';...
    '--title-in','no','draw title in/out of axes';...
    '--figtitle','',' Title shown in the figure.';...
    '--title4sentinel1','no','display Sentinel-1 A/B and IPF info in title.';...
    '--figsize','','figure size in inches - width and length';...
    '--dpi','','DPI - dot per inch - for display/write (default: 300).';...
    '--figext','','{.emf,.eps,.pdf,.png,.ps,.raw,.rgba,.svg,.svgz} File extension for figure output file (default: .png).';...
    '--fignum','','number of figure windows';...
    '--nrows','','subplot number in row';...
    '--ncols','','subplot number in column';...
    '--wspace','','width space between subplots in inches';...
    '--hspace','','height space between subplots in inches';...
    '--no-tight-layout','no','disable automatic tight layout for multiple subplots';...
    '--coord','','{radar,geo} Display in radar/geo coordination system (for geocoded file only; default: geo).';...
    '--animation','no','enable animation mode';...
    '--show-gps','no','Show UNR GPS location within the coverage.';...
    '--mask-gps','no','Mask out GPS stations not coincident with valid data pixels';...
    '--gps-label','no','Show GPS site name';...
    '--gps-ms','','Plot GPS value as scatter in size of ms**2 (default: 6).';...
    '--gps-comp','','{enu2los,hz2los,vert,up2los,horz} Plot GPS in color indicating deformation velocity direction';...
    '--gps-redo','no','Re-calculate GPS observations in LOS direction, instead of read from existing CSV file.';...
    '--ref-gps','','Reference GPS site';...
    '--ex-gps','','[EX_GPS_SITES [EX_GPS_SITES ...]] Exclude GPS sites, require --gps-comp.';...
    '--gps-start-date','','YYYYMMDD start date of GPS data, default is date of the 1st SAR acquisition';...
    '--gps-end-date','','YYYYMMDD start date of GPS data, default is date of the last SAR acquisition';...
    '--hz-az','','Azimuth angle (anti-clockwise from the north) of the horizontal movement in degrees E.g.: -90. for east  direction [default] 0.  for north direction Set to the azimuth angle of the strike-slip fault to show the fault-parallel displacement.';...
    '--mask','','mask file for display. "no" to turn OFF masking.';...
    '--mask-vmin','','hide pixels with mask value < vmin (default: None).';...
    '--mask-vmax','','hide pixels with mask value > vmax (default: None).';...
    '--zero-mask','no','mask pixels with zero value.';...
    '--coastline','','{110m,50m,10m} Draw coastline with specified resolution (default: None). This will enable --lalo-label option. Link: https://scitools.org.uk/cartopy/docs/latest/matplotlib/geoaxes.html#cartopy.mpl.geoaxes.GeoAxes.coastlines one subplot in geo-coordinates only';...
    '--lalo-label','no','Show N, S, E, W tick label for plot in geo-coordinate. Useful for final figure output. one subplot in geo-coordinates only';...
    '--lalo-step','','Lat/lon step for lalo-label option. one subplot in geo-coordinates only';...
    '--lalo-max-num','','Maximum number of lalo tick label (default: 3). one subplot in geo-coordinates only';...
    '--lalo-loc','','left right top bottom Draw lalo label in [left, right, top, bottom] (default: [1, 0, 0, 1]). one subplot in geo-coordinates only';...
    '--scalebar','','LEN X Y scale bar distance and location in ratio (default: [0.2, 0.2, 0.1]).distance in ratio of total width location in X/Y in ratio with respect to the lower left corner --scalebar 0.2 0.2 0.1  #for lower left  corner --scalebar 0.2 0.2 0.8  #for upper left  corner --scalebar 0.2 0.8 0.1  #for lower right corner --scalebar 0.2 0.8 0.8  #for upper right corner one subplot in geo-coordinates only';...
    '--noscalebar','no','do not display scale bar. one subplot in geo-coordinates only';...
    '--scalebar-pad','','scale bar label pad in ratio of scalebar width (default: 0.05). one subplot in geo-coordinates only';...
    '--pts-marker','','Marker of points of interest (default: k^).';...
    '--pts-ms','','Marker size for points of interest (default: 6.0).';...
    '--pts-yx','','Y X Point in Y/X';...
    '--pts-lalo','','LAT LON Point in Lat/Lon';...
    '--pts-file','','Text file for point(s) in lat/lon column';...
    '--ref-date','','Change reference date for display';...
    '--ref-lalo','','LAT LON Change referene point LAT LON for display';...
    '--ref-yx','','Y X Change referene point Y X for display';...
    '--noreference','no','do not show reference point';...
    '--ref-marker','','marker of reference pixel (default: ks).';...
    '--ref-size','','marker size of reference point (default: 6).';...
    '-o','','[OUTFILE [OUTFILE ...]], --outfile [OUTFILE [OUTFILE ...]] save the figure with assigned filename. By default, it''s calculated based on the input file name.';...
    '--save','no','save the figure';...
    '--nodisplay','no','save and do not display the figure';...
    '--update','no','enable update mode for save figure: skip running if 1) output file already exists AND 2) output file is newer than input file.';...
    '--sub-x','','XMIN XMAX subset display in x/cross-track/range direction';...
    '--sub-y','','YMIN YMAX subset display in y/along-track/azimuth direction';...
    '--sub-lat','','LATMIN LATMAX subset display in latitude';...
    '--sub-lon','','LONMIN LONMAX subset display in longitude';...
    };

tableapimintpytsview.Data = cell2table(paratable,'VariableNames',{'Parameters' 'Value' 'Information'});

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Other functions (in global)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Run the application
    function run_api_tsview(btn,event)
        cur_dataset = datasetapimintpytsview.Value;
        pref = cell(1);
        for i1 = 1 : length(cur_dataset)
            if isempty(strfind(cur_dataset{i1},'geo'))==0
                pref{i1} = 'geo/';
            else
                pref{i1} = '';
            end
        end

        % check the parameters
        paratablecheck = table2cell(tableapimintpytsview.Data);
        if length(cur_dataset)>1
            cmdi = [];
            for i1 = 1 : length(cur_dataset)
                cmdi = [cmdi,' ',cur_dataset{i1}];
            end
            paratablecheck{1,2} = cmdi;
        end
        cmd = ['tsview.py'];
        for i1 = 1 : length(cur_dataset)
            cmd = [cmd, ' ',pref{i1},cur_dataset{i1}];
        end
        for i1 = 1 : size(paratablecheck)
            if isempty(paratablecheck{i1,2}) == 0 & strcmp(paratablecheck{i1,2},'no') == 0
                if strcmp(paratablecheck{i1,2},'yes') == 1
                    cmd = [cmd,' ',paratablecheck{i1,1}];
                else
                    cmd = [cmd,' ',paratablecheck{i1,1},' ',paratablecheck{i1,2}];
                end
            end
        end

        % Write the command
        scripttoeval = ['scripttoeval_',miesar_para.id,'.sh'];
        fid = fopen(scripttoeval,'w');
        fprintf(fid,'cd %s\n',[pathmintpyprocessing]);
        fprintf(fid,'%s > %s/view.log &\n',cmd,miesar_para.cur);
        fclose(fid);

        % Run the script
        system(['chmod a+x ',scripttoeval]);
        if strcmp(computer,'MACI64') == 1
            %                     system('./runmacterminal.sh');
        else
            system(['./',scripttoeval]);
        end
        try
            delete(scripttoeval)
        end
    end
end
